pipeline:
  name: maven
  identifier: maven
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testinggithub
        repoName: java-hello-world-with-maven
        build: <+input>
  stages:
    - stage:
        name: java
        identifier: java
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: testinggithub
                    repoName: java-hello-world-with-maven
                    build:
                      type: branch
                      spec:
                        branch: main
