pipeline:
  name: maven
  identifier: maven
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testinggithub
        repoName: java-hello-world-with-maven
        build: <+input>
  stages:
    - stage:
        name: java
        identifier: java
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: IACgcptest
                    repoName: Java_app
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      mvn -version
                      mvn clean install
                      ls target/
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      target/jb-hello-world-maven-0.2.0.jar
                      ls -l target/jb-hello-world-maven-0.2.0.jar
                      -rw-r--r-- 1 user group 1234567 Nov 20 15:30 target/jb-hello-world-maven-0.2.0.jar
                      chmod 644 target/jb-hello-world-maven-0.2.0.jar

                      docker build -t my-app-image .
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: gcpbin
                    host: us-central1-docker.pkg.dev/smooth-keel-441611-d0/testing
                    projectID: smooth-keel-441611-d0
                    imageName: maven
                    tags:
                      - v1
